### ISSUE TITLE
Charts not loaded in standalone expo app

### ISSUE THREAD

**Issue by dreadful-dev** [fusioncharts/react-native-fusioncharts#23]
I'm trying to build standalone versions of my expo app to upload to the app stores, and when I build the app binaries and install on devices for testing, the charts no longer load like they did in development.

I followed the instructions in #2 to get running in development.

**Comment by ashok1994** [comment]
@dreadful-dev  May i know which version of react-native-fusioncharts and fusioncharts , you are using ?

**Comment by ashok1994** [comment]
Hi, @dreadful-dev  Meanwhile you can refer this repo [react native fusioncharts samples](https://github.com/fusioncharts/react-native-fusioncharts-samples) , which was created using `react-native init` not expo which works for dev and prod environment both.
We are looking into the problem for the expo app.

**Comment by rohanoid5** [comment]
Hi, @dreadful-dev in order to build your application using `expo`, you need to take a few additional steps. The steps are following:

1.  First of all you may have noticed in our [sample](https://github.com/fusioncharts/react-native-fusioncharts) code of `app.js` we use `this.libraryPath` to set our asset url `fusioncharts.html`. You need to do a slight modification here. 
In `app.js` instead of: 
`this.libraryPath = require('./assets/fusioncharts.html');`
do this:
`this.libraryPath = Asset.fromModule(require('./assets/fusioncharts.html'))};`
also make sure to import the following:
`import { Asset } from 'expo';`

2. Then in your project, run the following commands:
`$ rm -rf node_modules`
`$ npm install uglify-es@3.2.2 --save`
More info on this can be found [here](https://github.com/expo/expo/issues/1226#issuecomment-358758380).

3. Follow this [link](https://docs.expo.io/versions/latest/distribution/building-standalone-apps) to build your app

**Comment by dreadful-dev** [comment]
Awesome, thanks @rohanoid5. Your suggestion worked perfectly.

**Comment by ashok1994** [comment]
@rohanoid5   Lets add some foot notes for it in readme.md , closing for now
